In [ ]:
pip install pyreadstat

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyreadstat in /usr/local/lib/python3.7/dist-packages (1.1.9)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from pyreadstat) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.0->pyreadstat) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.0->pyreadstat) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.2.0->pyreadstat) (1.15.0)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_search_2018 = pd.read_spss('/content/drive/MyDrive/KHUDA/컨퍼런스/KHUDA_conference/data/02.국민여가활동조사/3.데이터/2018 국민여가활동조사_데이터.SAV')

In [ ]:
df_search_2018

,ID,SQ1,Q1A1,Q1A2,Q1A3,Q1A4,Q1A5,Q1A6,Q1A7,Q1A8,...,GUMO,GENDER,AGE_G1,EDU,FAM,MER,GAGU,CLA,INC,HANDICAP
0,1.0,서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,대도시,남성,20대,고졸,3인 이상,미혼,가구주 아님,무직자(전업주부/학생/기타),600만원 이상,해당사항없음
1,2.0,서울특별시,"A1 전시회 관람 (미술, 사진, 건축, 디자인 등)",NaN,NaN,NaN,A5 연극공연 관람(뮤지컬 포함),NaN,A7 영화관람,NaN,...,대도시,여성,50대,대졸이상,2인가구,기혼,가구주 아님,고용원이 없는 자영자,600만원 이상,해당사항없음
2,3.0,서울특별시,NaN,NaN,NaN,NaN,A5 연극공연 관람(뮤지컬 포함),NaN,A7 영화관람,NaN,...,대도시,남성,40대,대졸이상,3인 이상,기혼,가구주,임금봉급근로자,600만원 이상,해당사항없음
3,4.0,서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,"A8 연예공연 관람(쇼, 콘서트, 마술 쇼 등)",...,대도시,여성,30대,대졸이상,3인 이상,기혼,가구주 아님,무직자(전업주부/학생/기타),400-500만원,해당사항없음
4,5.0,서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,대도시,여성,60대,대졸이상,3인 이상,기혼,가구주 아님,무직자(전업주부/학생/기타),600만원 이상,해당사항없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10493,10996.0,제주특별자치도,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,중소도시,남성,50대,대졸이상,3인 이상,기혼,가구주,고용원이 없는 자영자,400-500만원,해당사항없음
10494,10997.0,제주특별자치도,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,중소도시,여성,50대,초졸이하,3인 이상,사별/이혼/기타,가구주,임금봉급근로자,500-600만원,해당사항없음
10495,10998.0,제주특별자치도,"A1 전시회 관람 (미술, 사진, 건축, 디자인 등)",A2 박물관 관람,NaN,NaN,A5 연극공연 관람(뮤지컬 포함),NaN,A7 영화관람,NaN,...,중소도시,남성,60대,대졸이상,2인가구,기혼,가구주,무직자(전업주부/학생/기타),200-300만원,해당사항없음
10496,10999.0,제주특별자치도,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,중소도시,남성,70세 이상,중졸,2인가구,기혼,가구주,무직자(전업주부/학생/기타),100만원미만,해당사항없음
10497,11000.0,제주특별자치도,"A1 전시회 관람 (미술, 사진, 건축, 디자인 등)",A2 박물관 관람,"A3 음악연주회 관람(클래식, 오페라 등)",NaN,A5 연극공연 관람(뮤지컬 포함),NaN,A7 영화관람,NaN,...,중소도시,여성,40대,대졸이상,2인가구,기혼,가구주 아님,고용원이 없는 자영자,400-500만원,해당사항없음

In [ ]:
df_search_2018[['Q1A47']]

             Q1A47
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
10493  E47 지역축제 참가
10494          NaN
10495          NaN
10496          NaN
10497  E47 지역축제 참가

[10498 rows x 1 columns]

In [ ]:
df_search_2018 = df_search_2018[df_search_2018['Q1A47'] == 'E47 지역축제 참가']

In [ ]:
# idx = df_search_2018[df_search_2018['v2'] == '서울'].index
# df_card = df_card.drop(idx)
# df_card

In [ ]:
df_search_2018

,ID,SQ1,Q1A1,Q1A2,Q1A3,Q1A4,Q1A5,Q1A6,Q1A7,Q1A8,...,GUMO,GENDER,AGE_G1,EDU,FAM,MER,GAGU,CLA,INC,HANDICAP
28,31.0,서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,대도시,남성,40대,대졸이상,3인 이상,기혼,가구주,임금봉급근로자,300-400만원,해당사항없음
29,32.0,서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,대도시,남성,50대,대졸이상,3인 이상,기혼,가구주,임금봉급근로자,400-500만원,해당사항없음
36,39.0,서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,대도시,남성,20대,대졸이상,3인 이상,미혼,가구주 아님,임금봉급근로자,500-600만원,해당사항없음
44,48.0,서울특별시,NaN,A2 박물관 관람,NaN,NaN,A5 연극공연 관람(뮤지컬 포함),NaN,A7 영화관람,"A8 연예공연 관람(쇼, 콘서트, 마술 쇼 등)",...,대도시,여성,20대,고졸,3인 이상,미혼,가구주 아님,무직자(전업주부/학생/기타),500-600만원,해당사항없음
47,51.0,서울특별시,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,대도시,여성,40대,대졸이상,3인 이상,기혼,가구주 아님,무직자(전업주부/학생/기타),300-400만원,해당사항없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10488,10991.0,제주특별자치도,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,중소도시,여성,20대,대졸이상,3인 이상,기혼,가구주 아님,임금봉급근로자,400-500만원,해당사항없음
10489,10992.0,제주특별자치도,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,중소도시,여성,30대,대졸이상,3인 이상,기혼,가구주 아님,무직자(전업주부/학생/기타),200-300만원,해당사항없음
10491,10994.0,제주특별자치도,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,중소도시,남성,40대,고졸,3인 이상,기혼,가구주,임금봉급근로자,600만원 이상,해당사항없음
10493,10996.0,제주특별자치도,NaN,NaN,NaN,NaN,NaN,NaN,A7 영화관람,NaN,...,중소도시,남성,50대,대졸이상,3인 이상,기혼,가구주,고용원이 없는 자영자,400-500만원,해당사항없음
10497,11000.0,제주특별자치도,"A1 전시회 관람 (미술, 사진, 건축, 디자인 등)",A2 박물관 관람,"A3 음악연주회 관람(클래식, 오페라 등)",NaN,A5 연극공연 관람(뮤지컬 포함),NaN,A7 영화관람,NaN,...,중소도시,여성,40대,대졸이상,2인가구,기혼,가구주 아님,고용원이 없는 자영자,400-500만원,해당사항없음

In [ ]:
df_search_2018 = df_search_2018[['Q2A1', 'Q2B1', 'Q2C1', 'Q2D1', 'Q2E1', 'Q2A2', 'Q2B2',
                                  'Q2C2', 'Q2D2', 'Q2E2', 'Q4A1', 'Q4A2', 'Q4A3', 'INC', 
                                  'Q45A1', 'Q45A2', 'MER', 'FAM', 'AGE_G1', 'Q38B1', 
                                  'GUMO', 'SIDO3', 'SIDO2', 'Q40A', 'Q37B1', 'Q37B2']]

In [ ]:
df_search_2018

,Q2A1,Q2B1,Q2C1,Q2D1,Q2E1,Q2A2,Q2B2,Q2C2,Q2D2,Q2E2,...,MER,FAM,AGE_G1,Q38B1,GUMO,SIDO3,SIDO2,Q40A,Q37B1,Q37B2
28,G70 산책 및 걷기,H86 친구만남/동호회 모임,A7 영화관람,F55 등산,E47 지역축제 참가,혼자서,친구(연인 포함)와 함께,혼자서,동호회(종교단체 등 포함)회원과 함께,가족(친척 포함)과 함께,...,기혼,3인 이상,40대,남자,대도시,서울/인천/경기,서울,NaN,NaN,0002명
29,D22 당구&포켓볼,"C17 스포츠 경기 간접관람- TV,DMB를 통한관람(축구, 야구, 농구, 배구 등)",G73 TV시청(DMB/IPTV 포함),"D20 농구, 배구, 야구, 축구, 족구",F64 음주,동호회(종교단체 등 포함)회원과 함께,혼자서,가족(친척 포함)과 함께,동호회(종교단체 등 포함)회원과 함께,직장 동료,...,기혼,3인 이상,50대,남자,대도시,서울/인천/경기,서울,NaN,NaN,0001명
36,F59 게임(온라인/모바일/콘솔게임 등),"C17 스포츠 경기 간접관람- TV,DMB를 통한관람(축구, 야구, 농구, 배구 등)","D23 볼링, 탁구",F64 음주,A7 영화관람,혼자서,혼자서,직장 동료,친구(연인 포함)와 함께,친구(연인 포함)와 함께,...,미혼,3인 이상,20대,남자,대도시,서울/인천/경기,서울,NaN,NaN,NaN
44,F58 인터넷 검색/채팅/1인 미디어 제작/SNS,H83 잡담/통화하기/문자보내기(모바일메신저 메시지 사용 포함),H86 친구만남/동호회 모임,G76 음악 감상,G73 TV시청(DMB/IPTV 포함),혼자서,친구(연인 포함)와 함께,친구(연인 포함)와 함께,혼자서,가족(친척 포함)과 함께,...,미혼,3인 이상,20대,여자,대도시,서울/인천/경기,서울,학생,NaN,NaN
47,G73 TV시청(DMB/IPTV 포함),H83 잡담/통화하기/문자보내기(모바일메신저 메시지 사용 포함),D29 헬스(보디빌딩)/에어로빅,H86 친구만남/동호회 모임,F63 쇼핑/외식,가족(친척 포함)과 함께,친구(연인 포함)와 함께,혼자서,친구(연인 포함)와 함께,친구(연인 포함)와 함께,...,기혼,3인 이상,40대,여자,대도시,서울/인천/경기,서울,전업주부,NaN,0001명
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10488,G73 TV시청(DMB/IPTV 포함),G76 음악 감상,F58 인터넷 검색/채팅/1인 미디어 제작/SNS,F59 게임(온라인/모바일/콘솔게임 등),G70 산책 및 걷기,가족(친척 포함)과 함께,혼자서,혼자서,혼자서,혼자서,...,기혼,3인 이상,20대,여자,중소도시,강원/제주,제주,NaN,0001명,NaN
10489,G73 TV시청(DMB/IPTV 포함),G76 음악 감상,G70 산책 및 걷기,E43 소풍/야유회,E46 테마파크가기/놀이공원/동물원/식물원 가기,혼자서,혼자서,가족(친척 포함)과 함께,가족(친척 포함)과 함께,가족(친척 포함)과 함께,...,기혼,3인 이상,30대,여자,중소도시,강원/제주,제주,전업주부,0002명,NaN
10491,"D20 농구, 배구, 야구, 축구, 족구",D25 수영,"C17 스포츠 경기 간접관람- TV,DMB를 통한관람(축구, 야구, 농구, 배구 등)",A7 영화관람,F55 등산,동호회(종교단체 등 포함)회원과 함께,혼자서,혼자서,혼자서,가족(친척 포함)과 함께,...,기혼,3인 이상,40대,남자,중소도시,강원/제주,제주,NaN,NaN,0002명
10493,G73 TV시청(DMB/IPTV 포함),G70 산책 및 걷기,F58 인터넷 검색/채팅/1인 미디어 제작/SNS,F63 쇼핑/외식,A7 영화관람,혼자서,혼자서,혼자서,가족(친척 포함)과 함께,가족(친척 포함)과 함께,...,기혼,3인 이상,50대,남자,중소도시,강원/제주,제주,NaN,NaN,NaN
10497,G73 TV시청(DMB/IPTV 포함),G76 음악 감상,F57 홈페이지/블로그 관리,F58 인터넷 검색/채팅/1인 미디어 제작/SNS,F63 쇼핑/외식,혼자서,혼자서,혼자서,동호회(종교단체 등 포함)회원과 함께,혼자서,...,기혼,2인가구,40대,여자,중소도시,강원/제주,제주,NaN,NaN,NaN

In [ ]:
df_search_2019 = pd.read_spss('/content/drive/MyDrive/KHUDA/컨퍼런스/KHUDA_conference/data/02.국민여가활동조사/3.데이터/2019 국민여가활동조사_데이터.sav')

In [ ]:
df_search_2019

,pid,q1_A,q1_A_m2,q1_A_m3,q1_A_m4,q1_A_m5,q1_A_m6,q1_A_m7,q1_A_m8,q1_A_m9,...,DM3,DM4,DM5,DM6,DM7,DM8,DM9,DM10,DM11,DM12
0,20.0,"1.전시회 관람 (미술, 사진, 건축, 디자인 등)",2.박물관 관람,5.연극공연 관람 (뮤지컬 포함),7.영화관람,NaN,NaN,NaN,NaN,NaN,...,대졸이상,3인 이상,기혼,가구주,임시근로자,400~500만원,대도시,수도권,인천,해당사항없음
1,21.0,"1.전시회 관람 (미술, 사진, 건축, 디자인 등)",2.박물관 관람,7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,...,대졸이상,3인 이상,기혼,가구주 아님,무직/기타,600만원 이상,대도시,수도권,인천,해당사항없음
2,23.0,보기 중 경험한 활동 없음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,대졸이상,2인,기혼,가구주,상용근로자,300~400만원,대도시,수도권,인천,해당사항없음
3,25.0,7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,대졸이상,3인 이상,기혼,가구주,상용근로자,600만원 이상,대도시,수도권,인천,해당사항없음
4,33.0,"1.전시회 관람 (미술, 사진, 건축, 디자인 등)","3.음악연주회 관람 (클래식, 오페라 등)",7.영화관람,"8.연예공연 관람 (쇼, 콘서트, 마술 쇼 등)",NaN,NaN,NaN,NaN,NaN,...,고졸,3인 이상,미혼,가구주 아님,무직/기타,600만원 이상,대도시,수도권,인천,해당사항없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10055,26078.0,7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,고졸,1인,사별/이혼/기타,가구주,상용근로자,200~300만원,대도시,대경권,대구,해당사항없음
10056,26079.0,7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,고졸,1인,사별/이혼/기타,가구주,고용원이 없는 자영업자,200~300만원,대도시,대경권,대구,해당사항없음
10057,26080.0,7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,고졸,2인,기혼,가구주,상용근로자,300~400만원,대도시,대경권,대구,해당사항없음
10058,26082.0,보기 중 경험한 활동 없음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,중졸,1인,사별/이혼/기타,가구주,임시근로자,100~200만원,대도시,대경권,대구,해당사항없음
10059,26083.0,보기 중 경험한 활동 없음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,대졸이상,2인,기혼,가구주,무직/기타,200~300만원,읍면지역,수도권,경기,해당사항없음

In [ ]:
df_search_2019.columns.values.tolist()

['pid',
 'q1_A',
 'q1_A_m2',
 'q1_A_m3',
 'q1_A_m4',
 'q1_A_m5',
 'q1_A_m6',
 'q1_A_m7',
 'q1_A_m8',
 'q1_A_m9',
 'q1_B',
 'q1_B_m2',
 'q1_B_m3',
 'q1_B_m4',
 'q1_B_m5',
 'q1_B_m6',
 'q1_B_m7',
 'q1_B_m8',
 'q1_C',
 'q1_C_m2',
 'q1_C_m3',
 'q1_C_m4',
 'q1_C_m5',
 'q1_D',
 'q1_D_m2',
 'q1_D_m3',
 'q1_D_m4',
 'q1_D_m5',
 'q1_D_m6',
 'q1_D_m7',
 'q1_D_m8',
 'q1_D_m9',
 'q1_D_m10',
 'q1_D_m11',
 'q1_D_m12',
 'q1_D_m13',
 'q1_D_m14',
 'q1_D_m15',
 'q1_D_m16',
 'q1_D_m17',
 'q1_D_m18',
 'q1_D_m19',
 'q1_E',
 'q1_E_m2',
 'q1_E_m3',
 'q1_E_m4',
 'q1_E_m5',
 'q1_E_m6',
 'q1_E_m7',
 'q1_E_m8',
 'q1_E_m9',
 'q1_E_m10',
 'q1_E_m11',
 'q1_E_m12',
 'q1_F',
 'q1_F_m2',
 'q1_F_m3',
 'q1_F_m4',
 'q1_F_m5',
 'q1_F_m6',
 'q1_F_m7',
 'q1_F_m8',
 'q1_F_m9',
 'q1_F_m10',
 'q1_F_m11',
 'q1_F_m12',
 'q1_F_m13',
 'q1_F_m14',
 'q1_F_m15',
 'q1_F_m16',
 'q1_F_m17',
 'q1_F_m18',
 'q1_F_m19',
 'q1_F_m20',
 'q1_F_m21',
 'q1_F_m22',
 'q1_F_m23',
 'q1_G',
 'q1_G_m2',
 'q1_G_m3',
 'q1_G_m4',
 'q1_G_m5',
 'q1_G_m6',
 'q1_G_m7',
 'q1_G_m8',
 'q1_G_m9',
 'q1_G_m10',
 'q1_H',
 'q1_H_m2',
 'q1_H_m3',
 'q1_H_m4',
 'q1_H_m5',
 'q1_H_m6',
 'q1_H_m7',
 'q1_H_m8',
 'q1_H_m9',
 'q1_H_m10',
 'q2_1_n2',
 'q2_1_n2_m2',
 'q2_1_n2_m3',
 'q2_1_n2_m4',
 'q2_1_n2_m5',
 'q2_2_1',
 'q2_3_1',
 'q2_4_1',
 'q2_4_1_n2',
 'q2_5_1',
 'q2_6_1',
 'q2_2_2',
 'q2_3_2',
 'q2_4_2',
 'q2_4_2_n2',
 'q2_5_2',
 'q2_6_2',
 'q2_2_3',
 'q2_3_3',
 'q2_4_3',
 'q2_4_3_n2',
 'q2_5_3',
 'q2_6_3',
 'q2_2_4',
 'q2_3_4',
 'q2_4_4',
 'q2_4_4_n2',
 'q2_5_4',
 'q2_6_4',
 'q2_2_5',
 'q2_3_5',
 'q2_4_5',
 'q2_4_5_n2',
 'q2_5_5',
 'q2_6_5',
 'q3',
 'q4',
 'q4_m2',
 'q4_m3',
 'q5',
 'q6',
 'q7',
 'q7_n2',
 'q8',
 'q9',
 'q9_1',
 'q10',
 'q11_1_A',
 'q11_2_A',
 'q11_3_A',
 'q11_1_B',
 'q11_2_B',
 'q11_3_B',
 'q11_1_C',
 'q11_2_C',
 'q11_3_C',
 'q11_1_D',
 'q11_2_D',
 'q11_3_D',
 'q11_1_E',
 'q11_2_E',
 'q11_3_E',
 'q11_1_F',
 'q11_2_F',
 'q11_3_F',
 'q11_1_G',
 'q11_2_G',
 'q11_3_G',
 'q11_1_H',
 'q11_2_H',
 'q11_3_H',
 'q12_1_A',
 'q12_2_A',
 'q12_3_A',
 'q12_1_B',
 'q12_2_B',
 'q12_3_B',
 'q12_1_C',
 'q12_2_C',
 'q12_3_C',
 'q12_1_D',
 'q12_2_D',
 'q12_3_D',
 'q12_1_E',
 'q12_2_E',
 'q12_3_E',
 'q12_1_F',
 'q12_2_F',
 'q12_3_F',
 'q12_1_G',
 'q12_2_G',
 'q12_3_G',
 'q12_1_H',
 'q12_2_H',
 'q12_3_H',
 'q13_1_1',
 'q13_2_1',
 'q13_3_1',
 'q13_4_1',
 'q13_1_2',
 'q13_2_2',
 'q13_3_2',
 'q13_4_2',
 'q14',
 'q14_1',
 'q14_2',
 'q14_2_n2',
 'q14_2_n3',
 'q14_2_n4',
 'q14_3',
 'q14_3_m2',
 'q14_3_m3',
 'q15',
 'q15_m2',
 'q15_m3',
 'q16',
 'q16_m2',
 'q16_m3',
 'q17',
 'q17_m2',
 'q17_m3',
 'q18_1',
 'q18_2',
 'q18_3',
 'q18_4',
 'q19',
 'q20',
 'q21_1',
 'q21_2',
 'q21_3',
 'q22',
 'q22_1',
 'q22_1_m2',
 'q22_1_1',
 'q22_1_2',
 'q23',
 'q23_1',
 'q23_1_m2',
 'q23_1_m3',
 'q23_1_m4',
 'q23_1_m5',
 'q23_1_m6',
 'q23_1_m7',
 'q24_1',
 'q24_2',
 'q25',
 'q26_1',
 'q26_2',
 'q26_3',
 'q26_4',
 'q26_5',
 'q26_6',
 'q26_7',
 'q26_1_n2',
 'q26_1_n2_m2',
 'q26_1_n2_m3',
 'q27_1',
 'q27_2',
 'q27_3',
 'q27_4',
 'q27_5',
 'q27_6',
 'q27_7',
 'q28',
 'q29',
 'q30',
 'q30_1',
 'q31',
 'q32',
 'q33',
 'q34',
 'q35_1',
 'q35_2',
 'q35_3',
 'q35_4',
 'q35_5',
 'q36',
 'q37',
 'q37_1_1',
 'q37_1_1_m2',
 'q37_1_1_m3',
 'q37_1_1_m4',
 'q37_1_1_m5',
 'q37_1_1_m6',
 'q37_1_1_m7',
 'q37_1_1_m8',
 'q37_1_1_m9',
 'q37_1_1_m10',
 'q37_1_1_m11',
 'q37_1_1_m12',
 'q37_1_1_m13',
 'q37_1_1_m14',
 'q37_1_1_m15',
 'q37_2_1',
 'q37_1_2',
 'q37_1_2_m2',
 'q37_1_2_m3',
 'q37_1_2_m4',
 'q37_1_2_m5',
 'q37_1_2_m6',
 'q37_1_2_m7',
 'q37_1_2_m8',
 'q37_1_2_m9',
 'q37_1_2_m10',
 'q37_1_2_m11',
 'q37_1_2_m12',
 'q37_1_2_m13',
 'q37_1_2_m14',
 'q37_1_2_m15',
 'q37_2_2',
 'q38',
 'q38_m2',
 'q38_m3',
 'q39',
 'q39_1',
 'q40',
 'q41',
 'q42',
 'q42_1',
 'q42_1_m2',
 'q42_1_m3',
 'q42_1_m4',
 'q42_1_2',
 'q42_1_3',
 'q42_1_4',
 'q43',
 'q43_1',
 'q43_2',
 'q43_3',
 'q43_4',
 'q43_5',
 'q44_1',
 'q44_1_1',
 'q44_1_1_m2',
 'q44_1_1_m3',
 'q44_1_1_m4',
 'q44_1_1_m5',
 'q44_1_1_m6',
 'q44_1_1_m7',
 'q44_1_1_m8',
 'q44_1_1_m9',
 'q44_1_1_m10',
 'q44_1_1_m11',
 'q44_1_1_m12',
 'q44_1_1_m13',
 'q44_1_1_m14',
 'q44_1_1_m15',
 'q44_1_1_m16',
 'q44_2',
 'q44_2_1',
 'q44_2_1_m2',
 'q44_2_1_m3',
 'q44_2_1_m4',
 'q44_2_1_m5',
 'q44_2_1_m6',
 'q44_2_1_m7',
 'q44_2_1_m8',
 'q44_2_1_m9',
 'q44_2_1_m10',
 'q44_2_1_m11',
 'q44_2_1_m12',
 'q44_2_1_m13',
 'q44_2_1_m14',
 'q44_2_1_m15',
 'q44_2_1_m16',
 'q45',
 'q45_1',
 'q45_1_m2',
 'q45_2',
 'q46',
 'q47',
 'q48',
 'q49_1',
 'q49_2',
 'wt',
 'DM1',
 'DM2',
 'DM3',
 'DM4',
 'DM5',
 'DM6',
 'DM7',
 'DM8',
 'DM9',
 'DM10',
 'DM11',
 'DM12']

In [ ]:
df_search_2019['q1_E']

0        38.문화유적방문 (고궁, 절, 유적지 등)
1                          40.삼림욕
2                         42.해외여행
3                     48.자동차 드라이브
4                         42.해외여행
                   ...
10055             39.자연명승 및 풍경 관람
10056             39.자연명승 및 풍경 관람
10057    38.문화유적방문 (고궁, 절, 유적지 등)
10058             39.자연명승 및 풍경 관람
10059    38.문화유적방문 (고궁, 절, 유적지 등)
Name: q1_E, Length: 10060, dtype: category
Categories (12, object): ['38.문화유적방문 (고궁, 절, 유적지 등)', '39.자연명승 및 풍경 관람', '40.삼림욕', '41.국내캠핑', ...,
                          '46.테마파크가기/놀이공원/동물원/식물원 가기', '47.지역축제 참가', '48.자동차 드라이브', '보기 중 경험한 활동 없음']

In [ ]:
df_search_2019_festival = df_search_2019[(df_search_2019['q1_E'] == '47.지역축제 참가') | (df_search_2019['q1_E_m2'] == '47.지역축제 참가') | (df_search_2019['q1_E_m3'] == '47.지역축제 참가') | 
                                         (df_search_2019['q1_E_m4'] == '47.지역축제 참가') | (df_search_2019['q1_E_m5'] == '47.지역축제 참가') | (df_search_2019['q1_E_m6'] == '47.지역축제 참가') | 
                                         (df_search_2019['q1_E_m7'] == '47.지역축제 참가') | (df_search_2019['q1_E_m8'] == '47.지역축제 참가') | (df_search_2019['q1_E_m9'] == '47.지역축제 참가') | 
                                         (df_search_2019['q1_E_m10'] == '47.지역축제 참가') | (df_search_2019['q1_E_m11'] == '47.지역축제 참가') | (df_search_2019['q1_E_m12'] == '47.지역축제 참가')]

In [ ]:
df_search_2019_festival

,pid,q1_A,q1_A_m2,q1_A_m3,q1_A_m4,q1_A_m5,q1_A_m6,q1_A_m7,q1_A_m8,q1_A_m9,...,DM3,DM4,DM5,DM6,DM7,DM8,DM9,DM10,DM11,DM12
0,20.0,"1.전시회 관람 (미술, 사진, 건축, 디자인 등)",2.박물관 관람,5.연극공연 관람 (뮤지컬 포함),7.영화관람,NaN,NaN,NaN,NaN,NaN,...,대졸이상,3인 이상,기혼,가구주,임시근로자,400~500만원,대도시,수도권,인천,해당사항없음
2,23.0,보기 중 경험한 활동 없음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,대졸이상,2인,기혼,가구주,상용근로자,300~400만원,대도시,수도권,인천,해당사항없음
7,48.0,7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,고졸,3인 이상,미혼,가구주 아님,무직/기타,500~600만원,대도시,수도권,인천,미등록
9,52.0,보기 중 경험한 활동 없음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,초졸이하,1인,기혼,가구주,무직/기타,100만원 미만,대도시,동남권,울산,장애등록
10,53.0,보기 중 경험한 활동 없음,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,고졸,2인,사별/이혼/기타,가구주,일용근로자,100~200만원,대도시,동남권,울산,해당사항없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10033,26026.0,7.영화관람,"8.연예공연 관람 (쇼, 콘서트, 마술 쇼 등)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,고졸,3인 이상,기혼,가구주,임시근로자,300~400만원,중소도시,수도권,경기,해당사항없음
10034,26030.0,"1.전시회 관람 (미술, 사진, 건축, 디자인 등)",7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,고졸,3인 이상,기혼,가구주,무직/기타,300~400만원,대도시,수도권,서울,해당사항없음
10038,26043.0,7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,초졸이하,1인,사별/이혼/기타,가구주,무직/기타,100만원 미만,읍면지역,수도권,경기,해당사항없음
10046,26058.0,"1.전시회 관람 (미술, 사진, 건축, 디자인 등)",7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,고졸,2인,기혼,가구주,무직/기타,300~400만원,대도시,수도권,서울,해당사항없음
10053,26073.0,7.영화관람,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,고졸,2인,기혼,가구주,고용원이 없는 자영업자,300~400만원,대도시,대경권,대구,해당사항없음